#!/data/data/com.termux/files/usr/bin/bash
# Prepare reboot persistence for the Ambimat jobs via Termux:Boot.
#
# Writes ~/.termux/boot/start-ambimat-jobs which, on every device boot, holds a
# wake-lock, starts crond, (re)installs the crontab lines, and runs the watchdog
# catch-up. Does NOT install the Termux:Boot app (must be installed by hand from
# F-Droid/Play — no APK downloads, no root). Reports honestly whether the app is
# present.
set -euo pipefail

HOME_DIR="${AMBIMAT_HOME:-/data/data/com.termux/files/home}"
BOOT_DIR="$HOME_DIR/.termux/boot"
BOOT_SCRIPT="$BOOT_DIR/start-ambimat-jobs"
LOGDIR="$HOME_DIR/ambimat_job_logs"
mkdir -p "$BOOT_DIR" "$LOGDIR"

cat > "$BOOT_SCRIPT" <<EOS
#!/data/data/com.termux/files/usr/bin/bash
# Auto-generated by install_boot_persistence.sh — runs at device boot (Termux:Boot).
PREFIX="/data/data/com.termux/files/usr"
export PATH="\$PREFIX/bin:\$PREFIX/bin/applets:/system/bin:/system/xbin"
export HOME="$HOME_DIR"
LOG="\$HOME/ambimat_job_logs/boot_startup.log"
mkdir -p "\$HOME/ambimat_job_logs"

echo "===== \$(date '+%F %T %z') boot: starting ambimat jobs =====" >> "\$LOG"

# 1. Keep the CPU awake / Termux foregrounded so crond survives (kept held).
termux-wake-lock 2>/dev/null && echo "\$(date '+%F %T %z') wake-lock acquired" >> "\$LOG" \\
  || echo "\$(date '+%F %T %z') wake-lock unavailable" >> "\$LOG"

# 2. Start crond if not already running.
if command -v crond >/dev/null 2>&1 && ! pgrep -x crond >/dev/null 2>&1; then
  crond && echo "\$(date '+%F %T %z') crond started" >> "\$LOG"
fi

# 2b. Start the USB SSH bridge (sshd) so remote access survives reboots too.
if command -v sshd >/dev/null 2>&1 && ! pgrep -x sshd >/dev/null 2>&1; then
  sshd && echo "\$(date '+%F %T %z') sshd started" >> "\$LOG"
fi

# 3. Ensure the crontab lines are installed (idempotent).
bash "\$HOME/seo_tracker/phone/schedule_daily.sh" install >> "\$LOG" 2>&1

# 4. After the network settles, run the watchdog to catch up anything missed.
sleep 45
bash "\$HOME/seo_tracker/phone/ensure_scheduler.sh" >> "\$LOG" 2>&1
echo "===== \$(date '+%F %T %z') boot: startup sequence done =====" >> "\$LOG"
EOS
chmod +x "$BOOT_SCRIPT"
echo "[boot] wrote $BOOT_SCRIPT"

if pm list packages 2>/dev/null | grep -q 'com.termux.boot'; then
  echo "[boot] Termux:Boot IS installed — reboot persistence is ACTIVE."
  echo "       (Open the Termux:Boot app once after install so Android arms the boot receiver.)"
else
  echo "[boot] Termux:Boot is NOT installed — reboot persistence is NOT yet active."
  echo "       Install 'Termux:Boot' from F-Droid/Play (same source as Termux), open it once,"
  echo "       then reboot. Until then, after a reboot run: ./phone/schedule_daily.sh install"
fi
echo
echo "IMPORTANT: reboot persistence only covers reboots. To stop Android killing"
echo "Termux (and crond) while powered on, also run: ./phone/battery_optimization.sh"
